multiple record types can be requested; many more comments

diff --git a/mdig b/mdig
--- a/mdig
+++ b/mdig
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+tabs 4
+
 custom_nameservers="Level3 209.244.0.3 209.244.0.4\n\
 Verisign 64.6.64.6 64.6.65.6\n\
 Google 8.8.8.8 8.8.4.4\n\
@@ -10,14 +12,19 @@ Cloudflare 1.1.1.1 1.0.0.1"
 
 
 digall() {
+	# loop through the requested record types and perform lookups
 	for r in ${record}; do
+		# DKIM is special, so take that into account now and during output
 		if [[ $r == 'TXT' ]]; then
 			dkimresults=$(dig +time=2 +tries=1 +noall +answer $r @$1 default._domainkey.$domain)
 		fi
+		# minimize amount of time spent perform dns lookups
+		# if time out is received, print it
 		results=$(dig +time=2 +tries=1 +noall +answer $r @$1 $domain)
 		if [[ $results =~ 'connection timed out' ]]; then
 			printf "\e[1;35mFAILED TO RETRIEVE ${r} RECORD WITHIN TIMEOUT\e[0m\n"
 		elif [[ ! -z $results ]]; then
+			# color coded record type output
 			case $r in
 				A)
 					printf "\e[0;32m${results}\e[0m\n"
@@ -32,7 +39,7 @@ digall() {
 					printf "\e[0;34m${results}\e[0m\n"
 					if [[ $dkimresults =~ 'connection timed out' ]]; then
 			            printf "\e[1;35mFAILED TO RETRIEVE ${r} RECORD WITHIN TIMEOUT\e[0m\n"
-					else
+					elif [[ ! -z $dkimresults ]]; then
 						printf "\e[0;34m${dkimresults}\e[0m\n"
 					fi
 					;;
@@ -60,12 +67,11 @@ resolve_auth_ns() {
 	rootns="${sub}.root-servers.net"
 
 	# Get tld authoritative NS
-	domainrootns=$(dig +time=2 +tries=1 +noall +authority @$rootns $domain | awk '{print$5}')
+	tldns=$(dig +time=2 +tries=1 +noall +authority @$rootns $domain | awk '{print$5}')
 
 	# Check for domain against tld's authoritative NS
-	# If found, set the domain's auth NS accordingly
-	# break out of loop
-	for ns in $domainrootns; do
+	# If found, set and break out of loop
+	for ns in $tldns; do
 		results=$(dig +time=2 +tries=1 +noall +authority @$ns $domain)
 		if [[ ! -z $(echo "$results" | awk '$4 == "NS" {print$4}') ]]; then
 			domainauthns=$(echo -e "$results" | awk '{print$5}')
@@ -73,37 +79,42 @@ resolve_auth_ns() {
 		fi
 	done
 
-	# If the parameter is not empty, get the IP address
-	# for each NS
+	# If auth nameservers were found, try to resolve them
 	if [[ ! -z $domainauthns ]]; then
 		for authns in $domainauthns; do
 			authnsip=$(dig +time=2 +tries=1 +short $authns|head -n1)
+			# if can resolve authns, create/append to nslist
+			# else inform that an ns couldn't be resolved
 			if [[ ! -z $authnsip ]]; then
 				if [[ ! -z $nslist ]]; then
 					nslist="$authns $authnsip\n$nslist"
 				else
 					nslist="$authns $authnsip"
 				fi
+			else
+				echo "Unable to resolve $authns"
 			fi
 		done
 	else
 		echo "No auth NS found for $domain"
-		exit 1
+		exit 11
 	fi
 }
 
-how2() {
-	echo -e "Usage: $0 <option> <domain>\n
+print_help() {
+	# print the helps
+	echo -e "Usage: $0 <options> <record(s)> <domain>\n
 Options:
-	-h|--how2 - prints this message
-	-b - check against authoritative and custom public nameserver list
-	-c - check against custom public nameserver list only\n
-Notes:
-	* defaults to checking authoritative only\n"
-	exit
+	-h|--help   - prints this message
+	   --all	- check against authoritative, custom, and local resolvers
+	-a|--auth   - check against authoritative resolver list (default)
+	-c|--custom - check against custom public resolver list only
+	-l|--local  - check against local resolvers found in /etc/resolv.conf\n"
+	exit 1
 }
 
 custom_list() {
+	# check for dns records from custom nameserver list
 	if [[ ! -z $custom_nameservers ]]; then
 		echo -e "===Custom nameserver list===\n"
 		while read provider primary secondary; do
@@ -112,20 +123,26 @@ custom_list() {
 				digall $ip | sed -r 's/^/\t/g'
 			done
 		done < <(echo -e "$custom_nameservers")
+	else
+		echo "No custom nameserver list defined"
 	fi
 }
 
 auth() {
+	# check for dns records from authoritative nameservers
 	if [[ ! -z $nslist ]]; then
 		echo -e "===Authoritative nameservers===\n"
 		while read provider ip; do
 			printf "\e[01;32mresults from $provider [ $ip ]\e[0m\n"
 			digall $ip | sed -r 's/^/\t/g'
 		done < <(echo -e $nslist)
+	else
+		echo "If you get this message, something happened with \$nslist between populating the variable and now. The script probably needs debugging if you got here. No nameserver list should have exited earlier."
 	fi
 }
 
 local_resolve() {
+	# check for dns records from local resolvers
 	local_ns=$(awk '/^nameserver/ {print$2}' /etc/resolv.conf)
 	if [[ ! -z $local_ns ]]; then
 		echo -e "===Local resolvers===\n"
@@ -133,19 +150,31 @@ local_resolve() {
 			printf "\e[01;32mresults from local resolver [ $ns ]\e[0m\n"
 			digall $ns | sed -r 's/^/\t/g'
 		done
+	else
+		echo "No nameservers found in /etc/resolv.conf"
 	fi
 }
 check_exist() {
+	# in short, this checks to see if the variable is already set.
+	# if not, assign it.
+	# the first argument is the name of the variable we want to check.
+	# using local, we're effectively setting the value of 'to_check'
+	# to the value of the actual variable we're checking.
 	local -n to_check="$1"
 	value="$2"
-    if [[ $to_check ]]; then
+	# if a variable is not empty and is not "record", return. we only
+	# want to be able to set multiple records to check. otherwise,
+	# set the variables accordingly.
+    if [[ ! -z $to_check && ${!to_check} != "record" ]]; then
 		return
 	elif [[ ${!to_check} == "domain" ]]; then
-		domain=$value
+		export "${!to_check}=${value}"
 	elif [[ ${!to_check} == "record" ]]; then
-		record=${value^^}
+		record="${record} ${value^^}"
 	elif [[ ${!to_check} == "which_ns" ]]; then
-		which_ns="$value"
+		export "${!to_check}=${value}"
+	elif [[ ${!to_check} == "ns_info" ]]; then
+		ns_info=1
     fi
 }
 
@@ -153,7 +182,6 @@ while (( "$#" )); do
 	case ${1,,} in
 		--nsinfo)
 			check_exist ns_info
-			ns_info=1
 			;;
 		--all)
 			check_exist which_ns all
@@ -168,7 +196,7 @@ while (( "$#" )); do
 			check_exist which_ns local
 			;;
 		-h|--help)
-			how2
+			print_help
 			;;
 		soa)
 			check_exist record $1
@@ -201,18 +229,24 @@ while (( "$#" )); do
 shift
 done
 
+# can't do lookups without a domain
 if [[ -z $domain ]]; then
 	echo "No domain found in arguments"
-	how2
+	print_help
 fi
+
+# if no records were specified, request them all!
 if [[ -z $record ]]; then
 	record="SOA A AAAA CAA MX NS TXT"
 fi
 
+# get authoritative nameservers
 resolve_auth_ns
 
+# print ns report of domain, bit nicer than trying to `whois | egrep -i 'name ?server'`
+# so many different ways they could be listed and sometime's not even on the same line!
 if [[ $ns_info ]]; then
-	echo -e "Authoritative nameserver report for: $domain\n"
+	echo -e "Authoritative nameserver report:\n"
 	while read provider ip; do
 		echo "$provider [$ip]"
 	done < <(echo -e $nslist) | column -t
